{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-postgres-backup-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    # This annotation maps your Kubernetes service account to your AWS IAM Role
    eks.amazonaws.com/role-arn: {{ .Values.backup.roleArn | quote }}
{{- end }}
